// <auto-generated />
using DialysisPatientTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DialysisPatientTracker.Migrations
{
    [DbContext(typeof(PatientMasterListDbContext))]
    [Migration("20190211211025_PatientMasterList")]
    partial class PatientMasterList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DialysisPatientTracker.Models.PatientMasterList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MedicalRecord");

                    b.Property<string>("Physician");

                    b.Property<int>("TreatmentDays");

                    b.HasKey("ID");

                    b.ToTable("PatientMasterLists");
                });
#pragma warning restore 612, 618
        }
    }
}
