// <auto-generated />
using DialysisPatientTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DialysisPatientTracker.Migrations.TreatmentMasterListDb
{
    [DbContext(typeof(TreatmentMasterListDbContext))]
    [Migration("20190212001115_int")]
    partial class @int
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DialysisPatientTracker.Models.TreatmentMasterList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessType");

                    b.Property<string>("BiCarb");

                    b.Property<string>("CaBath");

                    b.Property<string>("Comments");

                    b.Property<string>("DialyzerSize");

                    b.Property<string>("FirstName");

                    b.Property<int>("KBath");

                    b.Property<string>("LastName");

                    b.Property<string>("MedicalRecord");

                    b.Property<string>("NaBath");

                    b.Property<int>("PatientId");

                    b.Property<string>("Physician");

                    b.Property<string>("Temp");

                    b.Property<int>("TreatmentDays");

                    b.Property<string>("TreatmentTime");

                    b.HasKey("ID");

                    b.ToTable("TreatmentMasterLists");
                });
#pragma warning restore 612, 618
        }
    }
}
